
exports.seed = function(knex) {
  return knex('lists')
    .where({ name: 'beliefs' })
    .first()
    .then(row => {
      let list_id = row.id

      console.log('population list_id', list_id)

      return knex('options')
        .where({ list_id }) // delete existing
        .del()
        .then(function () {
          // Inserts seed entries
          return knex('options').insert([
            {value: "Other", list_id, sort: -1},
            {value: "Abundance", list_id},
            {value: "Acceptance", list_id},
            {value: "Accountability", list_id},
            {value: "Achievement", list_id},
            {value: "Adventure", list_id},
            {value: "Appreciation", list_id},
            {value: "Authenticity", list_id},
            {value: "Awareness", list_id},
            {value: "Balance", list_id},
            {value: "Beauty", list_id},
            {value: "Boldness", list_id},
            {value: "Bravery", list_id},
            {value: "Calm", list_id},
            {value: "Caring", list_id},
            {value: "Centeredness", list_id},
            {value: "Challenge", list_id},
            {value: "Change", list_id},
            {value: "Charity", list_id},
            {value: "Clarity", list_id},
            {value: "Collaboration", list_id},
            {value: "Comedy", list_id},
            {value: "Comfort", list_id},
            {value: "Commitment", list_id},
            {value: "Communication", list_id},
            {value: "Community", list_id},
            {value: "Compassion", list_id},
            {value: "Competition", list_id},
            {value: "Constancy", list_id},
            {value: "Creativity", list_id},
            {value: "Curiosity", list_id},
            {value: "Courage", list_id},
            {value: "Decisiveness", list_id},
            {value: "Depth", list_id},
            {value: "Determination", list_id},
            {value: "Discipline", list_id},
            {value: "Discovery", list_id},
            {value: "Diversity", list_id},
            {value: "Ease", list_id},
            {value: "Education", list_id},
            {value: "Effectiveness", list_id},
            {value: "Efficiency", list_id},
            {value: "Empathy", list_id},
            {value: "Equality", list_id},
            {value: "Excellence", list_id},
            {value: "Excitement", list_id},
            {value: "Expression", list_id},
            {value: "Fairness", list_id},
            {value: "Faith", list_id},
            {value: "Family", list_id},
            {value: "Flexibility", list_id},
            {value: "Forgiveness", list_id},
            {value: "Freedom", list_id},
            {value: "Friendship", list_id},
            {value: "Fun", list_id},
            {value: "Generosity", list_id},
            {value: "Goodness", list_id},
            {value: "Grace", list_id},
            {value: "Gratitude", list_id},
            {value: "Happiness", list_id},
            {value: "Hard Work", list_id},
            {value: "Health", list_id},
            {value: "Honesty", list_id},
            {value: "Honor", list_id},
            {value: "Humility", list_id},
            {value: "Imagination", list_id},
            {value: "Independence", list_id},
            {value: "Influence", list_id},
            {value: "Inner Peace", list_id},
            {value: "Innovation", list_id},
            {value: "Integrity", list_id},
            {value: "Intelligence", list_id},
            {value: "Joy", list_id},
            {value: "Justice", list_id},
            {value: "Kindness", list_id},
            {value: "Knowledge", list_id},
            {value: "Laughter", list_id},
            {value: "Learning", list_id},
            {value: "Leadership", list_id},
            {value: "Love", list_id},
            {value: "Loyalty", list_id},
            {value: "Mastery", list_id},
            {value: "Meaning", list_id},
            {value: "Mindfulness", list_id},
            {value: "Modesty", list_id},
            {value: "Mystery", list_id},
            {value: "Non‐judgment", list_id},
            {value: "Non‐violence", list_id},
            {value: "Observation", list_id},
            {value: "Openness", list_id},
            {value: "Optimism", list_id},
            {value: "Order", list_id},
            {value: "Organization", list_id},
            {value: "Passion", list_id},
            {value: "Patience", list_id},
            {value: "Peace", list_id},
            {value: "Persistence", list_id},
            {value: "Personal Growth", list_id},
            {value: "Pioneering", list_id},
            {value: "Pleasure", list_id},
            {value: "Poise", list_id},
            {value: "Positive Attitude", list_id},
            {value: "Power", list_id},
            {value: "Practicality", list_id},
            {value: "Privacy", list_id},
            {value: "Progress", list_id},
            {value: "Prosperity", list_id},
            {value: "Quality", list_id},
            {value: "Quiet", list_id},
            {value: "Realism", list_id},
            {value: "Recognition", list_id},
            {value: "Reliability", list_id},
            {value: "Resourcefulness", list_id},
            {value: "Respect", list_id},
            {value: "Responsibility", list_id},
            {value: "Risk", list_id},
            {value: "Romance", list_id},
            {value: "Security", list_id},
            {value: "Selflessness", list_id},
            {value: "Seriousness", list_id},
            {value: "Service", list_id},
            {value: "Sexuality", list_id},
            {value: "Silliness", list_id},
            {value: "Simplicity", list_id},
            {value: "Sincerity", list_id},
            {value: "Skillfulness", list_id},
            {value: "Spirit", list_id},
            {value: "Stability", list_id},
            {value: "Stillness", list_id},
            {value: "Strength", list_id},
            {value: "Style", list_id},
            {value: "Support", list_id},
            {value: "Teamwork", list_id},
            {value: "Timeliness", list_id},
            {value: "Tolerance", list_id},
            {value: "Tradition", list_id},
            {value: "Tranquility", list_id},
            {value: "Trust", list_id},
            {value: "Truth", list_id},
            {value: "Unity", list_id},
            {value: "Variety", list_id},
            {value: "Vision", list_id},
            {value: "Well‐being", list_id},
            {value: "Whimsy", list_id},
            {value: "Willingness", list_id},
            {value: "Wisdom",list_id}
          ])
        });
    })
    
};
